config/routes.rb
require 'sidekiq/web'

GitReports::Application.routes.draw do
  # Error pages.
  %w[404 422 500].each do |code|
    match code, to: "errors#error_#{code}", via: :all
  end

  # Authentication routes
  get '/login', to: 'authentications#login', as: 'login'
  get '/github_callback', to: 'authentications#callback'
  get '/logout', to: 'authentications#logout', as: 'logout'
  get '/login_rate_limited', to: 'authentications#login_rate_limited', as: 'login_rate_limited'

  # Repository routes
  get '/profile', to: 'repositories#index', as: 'profile'
  scope :issue do
    get ':username/:repositoryname', to: 'issues#new', as: 'repository_public', repositoryname: %r{[^\/]+}
    post ':username/:repositoryname', to: 'issues#create', repositoryname: %r{[^\/]+}
    get ':username/:repositoryname/submitted', to: 'issues#created', as: 'submitted', repositoryname: %r{[^\/]+}
  end

  resources :repositories, only: %i[show edit update] do
    collection do
      get :load_status
    end
  end

  # Sidekiq monitoring
  constraints ->(request) { User.find_by(id: request.session[:user_id])&.is_admin } do
    mount Sidekiq::Web => '/admin/sidekiq'
  end
end

app/models/repository.rb
class Repository < ApplicationRecord
  has_and_belongs_to_many :users, -> { order 'username ASC' }
  belongs_to :organization

  scope :user_owned, -> { where(organization: nil) }
  scope :with_user, ->(user) { joins(:users).where('users.id = ?', user) }

  validate :custom_field_length

  include HasUniqueUsers

  def access_token
    users.first.access_token
  end

  def holder_name
    if owner
      owner
    elsif organization
      organization.name
    else
      users.first.username
    end
  end

  def holder_path
    "https://github.com/#{holder_name}"
  end

  def construct_body(sub_name, email, email_public, details)
    body = ''
    body += "Submitter: #{sub_name}\r\n" unless sub_name.blank?
    body += "Email: #{email}\r\n" if email_public == 'on' && email.present?
    body += details unless details.blank?

    body
  end

  def display_or_name
    return display_name if display_name.present?
    name
  end

  def github_issues_path
    "#{holder_path}/#{name}/issues"
  end

  def github_issue_path(issue)
    "#{github_issues_path}/#{issue}"
  end

  private

  def custom_field_length
    %w[display_name issue_name prompt followup].each do |field|
      errors[field] << 'must be at least 5 characters' unless send(field).blank? || send(field).length >= 5
    end
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :ensure_signed_in!, only: [:index]
  before_action :ensure_own_repository!, except: %i[index load_status]

  def index
    @current_user = current_user
  end

  def show
    @repository = Repository.find(params[:id])
  end

  def edit
    @repository = Repository.find(params[:id])
  end

  def update
    @repository = Repository.find(params[:id])

    if @repository.update(repository_params)
      redirect_to repository_path(@repository)
    else
      render 'edit'
    end
  end

  def load_status
    render plain: Sidekiq::Status.complete?(session[:job_id])
  end

  private

  def repository_params
    params[:repository].permit(:display_name, :issue_name, :prompt, :followup, :labels, :allow_issue_title, :include_submitter_email, :is_active).merge(
      notification_emails: parse_emails(params[:repository][:notification_emails]),
      allow_issue_title: (params[:repository][:allow_issue_title] == 'yes'),
      include_submitter_email: (params[:repository][:include_submitter_email] == 'yes')
    )
  end

  def parse_emails(emails)
    valid_emails = []
    unless emails.nil?
      emails.split(/,|\n/).each do |full_email|
        next if full_email.blank?

        email = if full_email.index(/\<.+\>/)
                  full_email.match(/\<.*\>/)[0].gsub(/[\<\>]/, '').strip
                else
                  full_email.strip
                end
        email = email.delete('<').delete('>')
        valid_emails << email if ValidateEmail.valid?(email)
      end
    end
    valid_emails.join(', ')
  end
end

app/views/repositories/_repository.html.erb
<tr>
  <td>
    <%= link_to repo.name, repository_path(repo) %>
  </td>
  <td>
    <%= link_to "Edit", edit_repository_path(repo) %>
  </td>
  <td>
    <% if repo.is_active %>
      Active
    <% else %>
      Inactive
    <% end %>
  </td>
  <td>
    <% if repo.is_active %>
      <%= link_to "Deactivate", repository_path(repo, repository: { is_active: false }), method: :patch, data: { confirm: "Are you sure you want to deactivate repository '" + repo.name + "'?" } %>
    <% else %>
      <%= link_to "Activate", repository_path(repo, repository: { is_active: true }), method: :patch, data: { confirm: "Are you sure you want to activate repository '" + repo.name + "'?" } %>
    <% end %>
  </td>
  <td>
    <% if repo.is_active %>
      <%= link_to "View", repository_public_path(@current_user.username, repo.name) %>
    <% else %>
      -
    <% end %>
  </td>
</tr>

app/views/repositories/edit.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_for :repository, url: repository_path(@repository), method: :patch do |f| %>
      <legend>Update <%= @repository.name %></legend>
      <% if @repository.errors.any? %>
        <div class="row">
          <div class="col-xs-12">
            <h2><%= pluralize(@repository.errors.count, "error") %> prohibited
              this repository from being saved:</h2>
            <ul>
            <% @repository.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        </div>
      <% end %>

      <div class="row">
        <div class="col-xs-12">
          <div class="form-group">
            <%= f.label :display_name %>
            <p>
              <i>This is the project name that will be displayed when an anonymous user creates a new issue.</i>
            </p>
            <%= f.text_field :display_name, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :issue_name %>
            <p>
              <i>This is what will be set as the name of the new issue created on GitHub.</i>
            </p>
            <%= f.text_field :issue_name, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :prompt %>
            <p>
              <i>This is the message that will be displayed to an anonymous user when they create a new issue.  You can use <%= link_to "Markdown", "http://daringfireball.net/projects/markdown/" %>.</i>
            </p>
            <%= f.text_area :prompt, class: "form-control no-resize" %>
          </div>

          <div class="form-group">
            <%= f.label :followup %>
            <p>
              <i>This is the result message that will be displayed to an anonymous user after they submit a new issue.  You can use <%= link_to "Markdown", "http://daringfireball.net/projects/markdown/" %>.</i>
            </p>
            <%= f.text_area :followup, class: "form-control no-resize" %>
          </div>

          <div class="form-group">
            <%= f.label :labels %><br>
            <p>
            <i>This is the comma-separated list of labels that will be applied to the new issue created on GitHub (bug, enhancement, etc.).  They should match label options on your repository's <%= link_to "issues page", @repository.github_issues_path %>.</i>
          </p>
            <%= f.text_field :labels, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :notification_emails %><br>
            <p>
              <i>A notification email will be sent to these email(s) when an issue is submitted. Enter a comma-separated list.</i>
            </p>
            <%= f.text_field :notification_emails, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :allow_issue_title %><br>
            <p>
              <i>Allow anonymous users to set the title of the submitted issue on GitHub. If active, the repository page will include a field for the issue title.</i>
            </p>

            <div class="radio">
              <label>
                <%= f.radio_button :allow_issue_title, 'no', :checked => !@repository.allow_issue_title %>
                No
              </label>
            </div>
            <div class="radio">
              <label>
                <%= f.radio_button :allow_issue_title, 'yes', :checked => @repository.allow_issue_title %>
                Yes
              </label>
            </div>
          </div>

          <% if @repository.notification_emails.present? %>
            <div class="form-group">
              <%= f.label :include_submitter_email %><br>
              <p>
                <i>Require submitters to include an email. If active, submitter emails will be included in email notifications.</i>
              </p>

              <div class="radio">
                <label>
                  <%= f.radio_button :include_submitter_email, 'no', :checked => !@repository.include_submitter_email %>
                  No
                </label>
              </div>
              <div class="radio">
                <label>
                  <%= f.radio_button :include_submitter_email, 'yes', :checked => @repository.include_submitter_email %>
                  Yes
                </label>
              </div>
            </div>
          <% end %>

          <%= submit_tag "Update", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/repositories/index.html.erb
<div class="row">
  <div class="col-xs-12 col-md-9">
    <h2><%= @current_user.name %></h2>
    <h4><%= link_to @current_user.username, @current_user.github_path %></h4>
  </div>
  <div class="col-xs-12 col-md-3 text-right">
    <%= image_tag @current_user.avatar_url, alt: @current_user.name, class: "profile-img" %>
  </div>
</div>
<% if params[:refresh] %>
  <div id="repo-alert" class="row">
    <div class="col-xs-12">
      <div class="alert alert-info">
        <button class="close" data-dismiss="alert">×</button>
        <span id="repo-load-info">Refreshing repository information from GitHub...</span>
      </div>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-xs-12">
    <hr>
    <% if @current_user.repositories.user_owned.none? %>
      <h3>No Repositories</h3>
      <p>Get to work!</p>
    <% else %>
      <h3>Repositories</h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th width="60%">Repository Name</th>
            <th width="10%">Edit</th>
            <th width="10%">Status</th>
            <th width="10%">Toggle</th>
            <th width="10%">Public URL</th>
          </tr>
        </thead>
        <tbody>
          <% @current_user.repositories.user_owned.each do |repo| %>
            <%= render partial: "repository", locals: { repo: repo } %>
          <% end %>
        </tbody>
      </table>
    <% end %>

    <% @current_user.organizations.each do |org| %>
      <hr>
      <h3><%= org.name %></h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th width="60%">Repository Name</th>
            <th width="10%">Edit</th>
            <th width="10%">Status</th>
            <th width="10%">Toggle</th>
            <th width="10%">Public URL</th>
          </tr>
        </thead>
        <tbody>
          <% org.repositories.with_user(@current_user).each do |repo| %>
            <%= render partial: "repository", locals: { repo: repo } %>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/repositories/not_found.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <h3><%= t('repositories.not_found.label') %></h3>
    <p>
      <%= t('repositories.not_found.message') %>
    </p>
  </div>
</div>

app/views/repositories/repository.html.erb
<div class="row">
  <div class="col-xs-12">
    <h3><%= @repository.display_or_name %></h3>
    <hr>
    <p>
      <% if @repository.prompt.present? && @repository.prompt != "" %>
          <%= raw markdown @repository.prompt %>
      <% else %>
          Please enter your bug report or feature request, then click 'Submit'. If you're reporting a bug, try to
          include as many details as possible about what you were doing when the bug occurred- a detailed report makes a
          bug much easier to track down.
      <% end %>
    </p>
    <hr>
    <%= form_tag(repository_public_path(@repository.holder_name, @repository.name), method: :post) do %>
        <legend><%= t('submit_form.title') %></legend>
        <div class="row">
          <div class="col-xs-12">
            <div class="form-group">
              <%= label :name, t('submit_form.label.name') %>
              <%= text_field_tag :name, @name, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= label :email, t('submit_form.label.email') %>
              <%= email_field_tag :email, @email, class: 'form-control', :required => @repository.include_submitter_email %>
            </div>

            <div class="form-group">
              <%= label :email_public, t('submit_form.label.email_public') %>
              <%= check_box_tag :email_public, @email_public, class: 'form-control' %>
            </div>

            <% if @repository.allow_issue_title %>
                <div class="form-group">
                  <%= label :issue_title, t('submit_form.label.issue_title') %>
                  <%= text_field_tag :issue_title, @issue_title, class: 'form-control' %>
                </div>
            <% end %>

            <div class="form-group">
              <%= label :details, t('submit_form.label.details') %>
              <%= text_area_tag :details, @details, class: "form-control no-resize" %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-6">
            <p><%= t('submit_form.captcha_message') %></p>
            <%= show_simple_captcha(label: "") %><br>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-3">
            <%= submit_tag t('submit_form.label.submit'), class: "btn btn-primary" %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/repositories/repository_edit.html.erb
<div class="row">
  <div class="small-12 columns">
    <h3><%= @repository.name %></h3>
    <%= form_for :repository, url: repository_path(@repository), method: :patch do |f| %>
      <fieldset>
        <legend>Update Repository</legend>

        <% if @repository.errors.any? %>
        <div class="row">
          <div class="small-12 columns">
            <h2><%= pluralize(@repository.errors.count, "error") %> prohibited
              this repository from being saved:</h2>
            <ul>
            <% @repository.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        </div>
        <% end %>

        <div class="row">
          <div class="small-12 columns">
            <%= f.label :display_name %><br>
            <p>
              <i>This is the project name that will be displayed when an anonymous user creates a new issue.</i>
            </p>
            <%= f.text_field :display_name %>
          </div>
        </div>

        <div class="row">
          <div class="small-12 columns">
            <%= f.label :issue_name %><br>
            <p>
              <i>This is what will be set as the name of the new issue created on GitHub.</i>
            </p>
            <%= f.text_field :issue_name %>
          </div>
        </div>

        <div class="row">
          <div class="small-12 columns">
            <%= f.label :prompt %><br>
            <p>
              <i>This is the message that will be displayed to an anonymous user when they create a new issue.  You can use <%= link_to "Markdown", "http://daringfireball.net/projects/markdown/" %>.</i>
            </p>
            <%= f.text_area :prompt, class: "repository-textarea" %>
          </div>
        </div>

        <div class="row">
          <div class="small-12 columns">
            <%= f.label :followup %><br>
            <p>
              <i>This is the result message that will be displayed to an anonymous user after they submit a new issue.  You can use <%= link_to "Markdown", "http://daringfireball.net/projects/markdown/" %>.</i>
            </p>
            <%= f.text_area :followup, class: "repository-textarea" %>
          </div>
        </div>

        <div class="row">
          <div class="small-12 columns">
            <%= f.label :labels %><br>
            <p>
            <i>This is the comma-separated list of labels that will be applied to the new issue created on GitHub (bug, enhancement, etc.).  They should match label options on your repository's <%= link_to "issues page", @repository.github_issues_path %>.</i>
          </p>
            <%= f.text_field :labels %>
          </div>
        </div>

        <div class="row">
          <div class="small-12 columns">
            <%= f.label :notification_emails %><br>
            <p>
              <i>A notification email will be sent to these email(s) when an issue is submitted. Enter a comma-separated list.</i>
            </p>
            <%= f.text_field :notification_emails %>
          </div>
        </div>

        <div class="row">
          <div class="small-3 columns">
            <%= submit_tag "Update", class: "button small" %>
          </div>
        </div>

      </fieldset>
    <% end %>
  </div>
</div>

app/views/repositories/repository_show.html.erb
<div class="row">
  <div class="large-12 columns">
    <h3><%= @repository.name %></h3>
    <p>
      Owner: <%= link_to @repository.holder_name, @repository.holder_path %>
    </p>
    <p>
      Users:
      <% @repository.users.each do |user| %>
        <% if user != @repository.users.first %>
          ,
        <% end %>
        <%= link_to user.username, user.github_path %>
      <% end %>
    </p>
    <p>
      Status: <%= @repository.is_active ? "Active" : "Inactive" %>
    </p>
    <% if @repository.is_active %>
      <p>
        Public Link: <%= link_to "View", repository_public_path(@repository.holder_name, @repository.name) %>
      </p>
    <% end %>
    <hr>
    <p>
      <%= link_to "Edit", repository_edit_path(@repository) %> /
      <% if @repository.is_active %>
        <%= link_to "Deactivate", repository_deactivate_path(@repository), method: :post, data: { confirm: "Are you sure you want to deactivate repository '" + @repository.name + "'?" } %>
      <% else %>
        <%= link_to "Activate", repository_activate_path(@repository), method: :post, data: { confirm: "Are you sure you want to activate repository '" + @repository.name + "'?" } %>
      <% end %>
    </p>
    <hr>
    <h4>
      Display Name
    </h4>
    <p>
      <i>This is the project name that will be displayed when an anonymous user creates a new issue.</i>
    </p>
    <p>
      <% if @repository.display_name.present? %>
        <%= @repository.display_name %>
      <% else %>
        Not set
      <% end %>
    </p>
    <h4>
      Issue Name
    </h4>
    <p>
      <i>This is what will be set as the name of the new issue created on GitHub.</i>
    </p>
    <p>
      <% if @repository.issue_name.present? %>
        <%= @repository.issue_name %>
      <% else %>
        Not set
      <% end %>
    </p>
    <h4>
      Prompt
    </h4>
    <p>
      <i>This is the message that will be displayed to an anonymous user when they create a new issue.</i>
    </p>
    <p>
      <% if @repository.prompt.present? %>
        <%= @repository.prompt %>
      <% else %>
        Not set
      <% end %>
    </p>
    <h4>
      Follow Up
    </h4>
    <p>
      <i>This is the result message that will be displayed to an anonymous user after they submit a new issue.</i>
    </p>
    <p>
      <% if @repository.followup.present? %>
        <%= @repository.followup %>
      <% else %>
        Not set
      <% end %>
    </p>
    <h4>
      Labels
    </h4>
    <p>
      <i>This is the comma-separated list of labels that will be applied to the new issue created on GitHub (bug, enhancement, etc.).</i>
    </p>
    <p>
      <% if @repository.labels.present? %>
        <%= @repository.labels %>
      <% else %>
        Not set
      <% end %>
    </p>
    <h4>
      Notification Email(s)
    </h4>
    <p>
      <i>A notification email will be sent to these email(s) when an issue is submitted.</i>
    </p>
    <p>
      <% if @repository.notification_emails.present? %>
        <%= @repository.notification_emails %>
      <% else %>
        Not set
      <% end %>
    </p>
  </div>
</div>

app/views/repositories/repository_submitted.html.erb
<div class="row">
  <div class="large-12 columns">
    <h3><%= @repository.display_or_name %></h3>
    <hr>
    <p>
      <% if @repository.followup.present? && @repository.followup != "" %>
        <%= raw markdown @repository.followup %>
      <% else %>
        Thanks for submitting your report!  We'll look into it as soon as possible.
      <% end %>
    </p>
  </div>
</div>

app/views/repositories/show.erb
<div class="row">
  <div class="col-xs-12">
    <h3><%= @repository.name %></h3>
    <p>
      Owner: <%= link_to @repository.holder_name, @repository.holder_path %>
    </p>
    <p>
      Users:
      <% @repository.users.each do |user| %>
        <% if user != @repository.users.first %>
          ,
        <% end %>
        <%= link_to user.username, user.github_path %>
      <% end %>
    </p>
    <p>
      Status: <%= @repository.is_active ? "Active" : "Inactive" %>
    </p>
    <% if @repository.is_active %>
      <p>
        Public Link: <%= link_to "View", repository_public_path(@repository.holder_name, @repository.name) %>
      </p>
    <% end %>
    <hr>
    <p>
      <%= link_to "Edit", edit_repository_path(@repository) %> /
      <% if @repository.is_active %>
        <%= link_to "Deactivate", repository_path(@repository, repository: { is_active: false }), method: :patch, data: { confirm: "Are you sure you want to deactivate repository '" + @repository.name + "'?" } %>
      <% else %>
        <%= link_to "Activate", repository_path(@repository, repository: { is_active: true }), method: :patch, data: { confirm: "Are you sure you want to activate repository '" + @repository.name + "'?" } %>
      <% end %>
    </p>
    <hr>
    <h4>
      Display Name
    </h4>
    <p>
      <i>This is the project name that will be displayed when an anonymous user creates a new issue.</i>
    </p>
    <p>
      <% if @repository.display_name.present? %>
        <%= @repository.display_name %>
      <% else %>
        Not set
      <% end %>
    </p>
    <h4>
      Issue Name
    </h4>
    <p>
      <i>This is what will be set as the name of the new issue created on GitHub.</i>
    </p>
    <p>
      <% if @repository.issue_name.present? %>
        <%= @repository.issue_name %>
      <% else %>
        Not set
      <% end %>
    </p>
    <h4>
      Prompt
    </h4>
    <p>
      <i>This is the message that will be displayed to an anonymous user when they create a new issue.</i>
    </p>
    <p>
      <% if @repository.prompt.present? %>
        <%= @repository.prompt %>
      <% else %>
        Not set
      <% end %>
    </p>
    <h4>
      Follow Up
    </h4>
    <p>
      <i>This is the result message that will be displayed to an anonymous user after they submit a new issue.</i>
    </p>
    <p>
      <% if @repository.followup.present? %>
        <%= @repository.followup %>
      <% else %>
        Not set
      <% end %>
    </p>
    <h4>
      Labels
    </h4>
    <p>
      <i>This is the comma-separated list of labels that will be applied to the new issue created on GitHub (bug, enhancement, etc.).</i>
    </p>
    <p>
      <% if @repository.labels.present? %>
        <%= @repository.labels %>
      <% else %>
        Not set
      <% end %>
    </p>
    <h4>
      Notification Email(s)
    </h4>
    <p>
      <i>A notification email will be sent to these email(s) when an issue is submitted.</i>
    </p>
    <p>
      <% if @repository.notification_emails.present? %>
        <%= @repository.notification_emails %>
      <% else %>
        Not set
      <% end %>
    </p>
    <h4>
      Custom Issue Titles
    </h4>
    <p>
      <b><%= @repository.allow_issue_title ? 'Yes' : 'No' %></b>: Users are <%= 'not' unless @repository.allow_issue_title %> permitted to set the issue title on GitHub.
    </p>
    <h4>
      Submitter Email Inclusion
    </h4>
    <p>
      <b><%= @repository.include_submitter_email ? 'Yes' : 'No' %></b>: User emails are <%= 'not' unless @repository.include_submitter_email %> included in notification emails.
    </p>
  </div>
</div>

app/views/repositories/submitted.erb
<div class="row">
  <div class="col-xs-12">
    <h3><%= @repository.display_or_name %></h3>
    <hr>
    <p>
      <% if @repository.followup.present? && @repository.followup != "" %>
        <%= raw markdown @repository.followup %>
      <% else %>
        Thanks for submitting your report!  We'll look into it as soon as possible.
      <% end %>
    </p>
  </div>
</div>