config/routes.rb
require 'sidekiq/web'

GitReports::Application.routes.draw do
  # Error pages.
  %w[404 422 500].each do |code|
    match code, to: "errors#error_#{code}", via: :all
  end

  # Authentication routes
  get '/login', to: 'authentications#login', as: 'login'
  get '/github_callback', to: 'authentications#callback'
  get '/logout', to: 'authentications#logout', as: 'logout'
  get '/login_rate_limited', to: 'authentications#login_rate_limited', as: 'login_rate_limited'

  # Repository routes
  get '/profile', to: 'repositories#index', as: 'profile'
  scope :issue do
    get ':username/:repositoryname', to: 'issues#new', as: 'repository_public', repositoryname: %r{[^\/]+}
    post ':username/:repositoryname', to: 'issues#create', repositoryname: %r{[^\/]+}
    get ':username/:repositoryname/submitted', to: 'issues#created', as: 'submitted', repositoryname: %r{[^\/]+}
  end

  resources :repositories, only: %i[show edit update] do
    collection do
      get :load_status
    end
  end

  # Sidekiq monitoring
  constraints ->(request) { User.find_by(id: request.session[:user_id])&.is_admin } do
    mount Sidekiq::Web => '/admin/sidekiq'
  end
end

app/helpers/layout_helper.rb
module LayoutHelper
  TITLE = 'Git Reports'.freeze
  DESCRIPTION = 'Git Reports is a free service that lets you set up a stable URL for anonymous users to submit bugs and other Issues to your GitHub repositories.'.freeze
  KEYWORDS = 'GitHub, git, issue, report, bug'.freeze

  def default_meta
    {
      description: DESCRIPTION,
      keywords: KEYWORDS,
      title: TITLE,
      icon: '/favicon.ico',
      viewport: 'width=device-width, initial-scale=1.0',
      og: {
        title: TITLE,
        url: request.url,
        site_name: TITLE,
        description: DESCRIPTION,
        image: 'https://gitreports.com/images/alarm.png',
        type: 'website'
      }
    }
  end

  def bootstrap_class_for(flash_type)
    case flash_type.to_sym
    when :success
      'alert-success'
    when :error
      'alert-danger'
    when :notice
      'alert-info'
    end
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class='footer'>
  <div class='container'>
    <hr />

    <div class='row'>
      <div class='col-xs-12 col-md-3'>
        &copy; <%= Time.now.year %> <%= link_to 'Zach Schneider', 'https://schneid.io' %>  
      </div>
      <div class='col-xs-12 col-md-9 footer-links'>
        <div class='pull-right'>
          <%= link_to 'Home', root_path %>
          <%= link_to 'About', page_path('about') %>
          <%= link_to 'Tutorial', page_path('tutorial') %>
        </div>
      </div>
    </div>
  </div>
  
  <% if ENV['GOOGLE_ANALYTICS_CODE'] %>
    <%= javascript_tag do %>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', '<%= ENV['GOOGLE_ANALYTICS_CODE'] %>', '<%= request.host %>');
      ga('send', 'pageview');
    <% end %>
  <% end %>
</footer>

app/views/layouts/_header.html.erb
<nav class='navbar navbar-default'>
  <div class='container'>
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#bs-nav' aria-expanded='false'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <%= link_to 'Git Reports', root_path, class: 'navbar-brand' %>
    </div>

    <div class='collapse navbar-collapse' id='bs-nav'>
      <ul class='nav navbar-nav navbar-right'>
        <% if signed_in? %>
          <li class='dropdown'>
            <%= link_to profile_path, class: 'dropdown-toggle', data: { toggle: 'dropdown' }, role: 'button', aria: { haspopup: 'true', expanded: 'false' } do %>
              <%= current_user.username %> <span class='caret'></span>
            <% end %>

            <ul class='dropdown-menu nav-menu'>
              <li><%= link_to 'Profile', profile_path %></li>
              <li><%= link_to 'Logout', logout_path %></li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to 'Login', login_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags(default_meta) %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag *webpack_asset_paths('application', extension: 'css') %>
    <%= javascript_include_tag *webpack_asset_paths('application', extension: 'js') %>
  </head>

  <body>
    <div class='flex-body'>
      <%= render partial: 'layouts/header' %>

      <main>
        <div class='container'>
          <%= render partial: 'layouts/flash' %>

          <%= yield %>
        </div>
      </main>

      <%= render partial: 'layouts/footer' %>
    </div>
  </body>
</html>